# ComfyUI服务器配置
comfyui_server:
  url: "http://127.0.0.1:8188/prompt"
  timeout: 30  # 请求超时时间(秒)

# 文件路径配置
paths:
  input_dir: "D:/AIGC/ComfyUI/input"
  output_dir: "D:/AIGC/ComfyUI/output"

# Gradio服务器配置
gradio_server:
  server_name: "127.0.0.1"
  cutout_server_port: 7860
  image_upscale_server_port: 7870
  remove_object_server_port: 7880
  share: true