# ComfyUI服务器配置
comfyui_server:
  url: "http://127.0.0.1:8188/prompt"
  timeout: 30  # 请求超时时间(秒)

# 文件路径配置
paths:
  input_dir: "{REPLEASE_YOUR_COMFYUI_INPUT_DIR}"
  output_dir: "{REPLEASE_YOUR_COMFYUI_OUTPUT_DIR}"
  clipspace_dir: "{REPLEASE_YOUR_COMFYUI_CLIPSPACE_DIR}"

# Gradio服务器配置
gradio_server:
  server_name: "0.0.0.0"
  rmbg_server_port: 7860
  image_upscale_server_port: 7870
  remove_object_server_port: 7880
  manual_remove_object_server_port: 7881
  image_extend_server_port: 7890
  fill_repaint_server_port: 7891
  fill_replace_server_port: 7892
  integrated_app_port: 7899
  share: true

# 钉钉推送配置
dingtalk:
  enabled: true
  webhook: "{REPLEASE_YOUR_WEBHOOK_ADDRESS}"
  secret: "{REPLEASE_YOUR_SECRET}"